import { generateId } from "../../lib/id"

function product(data) {
  return { id: generateId(), ...data }
}

export const SEED_BRANDS = [
  {
    id: generateId(),
    brandName: "MitWellness",
    description: "Premium kratom and botanical wellness products for independent retailers.",
    website: "mitwellness.com",
    mainContact: "Alex Rivera",
    contactEmail: "alex@mitwellness.com",
    contactPhone: "(512) 555-0201",
    commissionDefault: 12,
    status: "Active",
    notes: "Strong performer in Austin metro. Reorder cycle every 2 weeks.",
    monthlySales: 18400,
    products: [
      product({ productName: "Green Maeng Da Caps", sku: "MW-GMD-60", category: "Tinctures", distributorPrice: 18, wholesalePrice: 24, msrp: 39.99, commissionOverride: null, notes: "" }),
      product({ productName: "Calm Blend Shot", sku: "MW-CBS-12", category: "Drinks", distributorPrice: 22, wholesalePrice: 30, msrp: 49.99, commissionOverride: 14, notes: "New launch — push samples" }),
    ],
    noteEntries: [],
    createdAt: "2024-08-01T08:00:00.000Z",
    updatedAt: "2025-06-28T10:00:00.000Z",
  },
  {
    id: generateId(),
    brandName: "Thrive Supreme",
    description: "Functional mushroom supplements and adaptogen blends.",
    website: "thrivesupreme.co",
    mainContact: "Jordan Lee",
    contactEmail: "jordan@thrivesupreme.co",
    contactPhone: "(737) 555-0312",
    commissionDefault: 15,
    status: "Active",
    notes: "Expanding into smoke shops. Request endcap displays.",
    monthlySales: 22100,
    products: [
      product({ productName: "Lion's Mane Focus", sku: "TS-LMF-90", category: "Tinctures", distributorPrice: 28, wholesalePrice: 38, msrp: 59.99, commissionOverride: null, notes: "" }),
      product({ productName: "Daily Immunity Gummies", sku: "TS-DIG-30", category: "Edibles", distributorPrice: 15, wholesalePrice: 22, msrp: 34.99, commissionOverride: null, notes: "" }),
      product({ productName: "Reishi Sleep Drops", sku: "TS-RSD-60", category: "Tinctures", distributorPrice: 26, wholesalePrice: 35, msrp: 54.99, commissionOverride: 18, notes: "" }),
    ],
    noteEntries: [],
    createdAt: "2024-09-15T08:00:00.000Z",
    updatedAt: "2025-06-25T14:00:00.000Z",
  },
  {
    id: generateId(),
    brandName: "NOKO",
    description: "Zero-nicotine herbal smoke alternatives and hemp pre-rolls.",
    website: "nokosmoke.com",
    mainContact: "Sam Ortiz",
    contactEmail: "sam@nokosmoke.com",
    contactPhone: "(512) 555-0448",
    commissionDefault: 10,
    status: "Active",
    notes: "High velocity SKU. Keep Sunrise Smoke Shop stocked.",
    monthlySales: 31200,
    products: [
      product({ productName: "Original Blend Pre-Roll 5pk", sku: "NK-OB-5", category: "Pre-Rolls", distributorPrice: 12, wholesalePrice: 18, msrp: 29.99, commissionOverride: null, notes: "" }),
      product({ productName: "Mint Chill Pre-Roll 5pk", sku: "NK-MC-5", category: "Pre-Rolls", distributorPrice: 12, wholesalePrice: 18, msrp: 29.99, commissionOverride: null, notes: "" }),
      product({ productName: "NOKO Display Unit", sku: "NK-DU-01", category: "Accessories", distributorPrice: 45, wholesalePrice: 65, msrp: 99.99, commissionOverride: 8, notes: "Free with 50+ unit order" }),
    ],
    noteEntries: [],
    createdAt: "2024-07-01T08:00:00.000Z",
    updatedAt: "2025-06-29T09:00:00.000Z",
  },
  {
    id: generateId(),
    brandName: "Sherpa",
    description: "Himalayan-inspired hemp flower and concentrate line.",
    website: "sherpahemp.com",
    mainContact: "Priya Sharma",
    contactEmail: "priya@sherpahemp.com",
    contactPhone: "(303) 555-0177",
    commissionDefault: 14,
    status: "Active",
    notes: "Colorado accounts performing well. Texas expansion in progress.",
    monthlySales: 15800,
    products: [
      product({ productName: "Base Camp Flower 3.5g", sku: "SH-BC-35", category: "Flower", distributorPrice: 20, wholesalePrice: 28, msrp: 45.99, commissionOverride: null, notes: "" }),
      product({ productName: "Summit Live Resin 1g", sku: "SH-SLR-1", category: "Concentrates", distributorPrice: 25, wholesalePrice: 35, msrp: 55.99, commissionOverride: 16, notes: "" }),
    ],
    noteEntries: [],
    createdAt: "2025-01-10T08:00:00.000Z",
    updatedAt: "2025-06-20T11:00:00.000Z",
  },
  {
    id: generateId(),
    brandName: "Totally Baked",
    description: "Premium THC and CBD edibles with bold branding for dispensaries.",
    website: "totallybaked.com",
    mainContact: "Chris Nguyen",
    contactEmail: "chris@totallybaked.com",
    contactPhone: "(512) 555-0555",
    commissionDefault: 13,
    status: "Active",
    notes: "Seasonal flavors rotate quarterly. Check Q3 menu.",
    monthlySales: 27600,
    products: [
      product({ productName: "Cosmic Brownie 100mg", sku: "TB-CB-100", category: "Edibles", distributorPrice: 8, wholesalePrice: 12, msrp: 19.99, commissionOverride: null, notes: "" }),
      product({ productName: "Galaxy Gummies 10pk", sku: "TB-GG-10", category: "Edibles", distributorPrice: 14, wholesalePrice: 20, msrp: 32.99, commissionOverride: null, notes: "" }),
      product({ productName: "Nebula Chocolate Bar", sku: "TB-NCB-1", category: "Edibles", distributorPrice: 10, wholesalePrice: 15, msrp: 24.99, commissionOverride: 15, notes: "" }),
    ],
    noteEntries: [],
    createdAt: "2024-06-01T08:00:00.000Z",
    updatedAt: "2025-06-27T16:00:00.000Z",
  },
  {
    id: generateId(),
    brandName: "HYE Harvest",
    description: "Farm-direct hemp flower and small-batch pre-rolls from Texas growers.",
    website: "hyeharvest.com",
    mainContact: "Morgan Ellis",
    contactEmail: "morgan@hyeharvest.com",
    contactPhone: "(512) 555-0666",
    commissionDefault: 11,
    status: "Prospect",
    notes: "New partnership — samples sent to 3 accounts. Awaiting feedback.",
    monthlySales: 4200,
    products: [
      product({ productName: "Texas Haze 3.5g", sku: "HY-TH-35", category: "Flower", distributorPrice: 18, wholesalePrice: 25, msrp: 39.99, commissionOverride: null, notes: "" }),
      product({ productName: "Field Notes Pre-Roll 2pk", sku: "HY-FN-2", category: "Pre-Rolls", distributorPrice: 9, wholesalePrice: 14, msrp: 22.99, commissionOverride: null, notes: "" }),
    ],
    noteEntries: [],
    createdAt: "2025-05-01T08:00:00.000Z",
    updatedAt: "2025-06-22T08:00:00.000Z",
  },
  {
    id: generateId(),
    brandName: "Magic Dose",
    description: "Micro-dose THC beverages and fast-acting nano gummies.",
    website: "magicdose.co",
    mainContact: "Taylor Brooks",
    contactEmail: "taylor@magicdose.co",
    contactPhone: "(737) 555-0888",
    commissionDefault: 16,
    status: "Paused",
    notes: "Paused pending label compliance update. Expected resume Aug 2025.",
    monthlySales: 0,
    products: [
      product({ productName: "Sparkling Lemon 2.5mg", sku: "MD-SL-4", category: "Drinks", distributorPrice: 16, wholesalePrice: 24, msrp: 38.99, commissionOverride: null, notes: "" }),
      product({ productName: "Nano Gummy Sampler", sku: "MD-NG-SMP", category: "Edibles", distributorPrice: 12, wholesalePrice: 18, msrp: 28.99, commissionOverride: 18, notes: "" }),
    ],
    noteEntries: [],
    createdAt: "2024-11-01T08:00:00.000Z",
    updatedAt: "2025-06-01T10:00:00.000Z",
  },
]
